apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thorntail-istio-circuit-breaker-delayed-name
spec:
  hosts:
    - thorntail-istio-circuit-breaker-name
  http:
    - fault:
        delay:
          percent: 50
          fixedDelay: 1s
      route:
        - destination:
            port:
              number: 8080
            host: thorntail-istio-circuit-breaker-name